export const ADD_ARTICLE = 'ADD_ARTICLE';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_ERROR = 'FETCH_USERS_REQUEST';
